- platform: template
  sensors:
    zte_network_type:
      friendly_name: "Network type"
      unique_id: sensor.zte_network_type
      value_template: "{{ state_attr('sensor.zte_router_info', 'network_type') }}"
    zte_wan_ipaddr:
      friendly_name: "WAN IP address"
      unique_id: sensor.zte_wan_ipaddr
      value_template: "{{ state_attr('sensor.zte_router_info', 'wan_ipaddr') }}"
    zte_5g_sinr:
      friendly_name: "5G SINR"
      unique_id: sensor.zte_5g_sinr
      value_template: "{{ state_attr('sensor.zte_router_info', 'Z5g_SINR') }}"
      unit_of_measurement: "dB"
    zte_5g_rsrp:
      friendly_name: "5G RSRP"
      unique_id: sensor.zte_5g_rsrp
      value_template: "{{ state_attr('sensor.zte_router_info', 'Z5g_rsrp') }}"
      unit_of_measurement: "dBm"
    zte_lte_monthly_transfer_usage:
      friendly_name: "Monthly usage"
      unique_id: sensor.zte_lte_monthly_transfer_usage
      value_template: '{{ ((state_attr("sensor.zte_router_info", "monthly_tx_bytes") |float + state_attr("sensor.zte_router_info", "monthly_rx_bytes") |float ) / 1024 / 1024 / 1024) | round(2) }}'
      unit_of_measurement: "GB"
    zte_realtime_download_speed:
      friendly_name: "Realtime download speed"
      unique_id: sensor.realtime_rx_thrpt
      value_template: '{{ ((state_attr("sensor.zte_router_info", "realtime_rx_thrpt") |float) / 1024 / 1024) | round(2) }}'
      unit_of_measurement: "MB/s"
    zte_realtime_upload_speed:
      friendly_name: "Realtime upload speed"
      unique_id: sensor.realtime_tx_thrpt
      value_template: '{{ ((state_attr("sensor.zte_router_info", "realtime_tx_thrpt") |float) / 1024 / 1024) | round(2) }}'
      unit_of_measurement: "MB/s"

- platform: command_line
  name: "ZTE Last SMS values"
  unique_id: sensor.zte_last_sms_values
  command: "/usr/bin/python3 /config/python_scripts/zte_tool.py 1"
  json_attributes:
    - id
    - content
    - number
  value_template: "{{ value_json.id }}"
  scan_interval: 900

- platform: command_line
  name: "ZTE SMS Memory left"
  unique_id: sensor.zte_sms_memory_left
  command: "/usr/bin/python3 /config/python_scripts/zte_tool.py 6"
  #  value_template: "{{ value_json.messages }}"
  scan_interval: 800

- platform: command_line
  name: "ZTE Router info"
  unique_id: sensor.zte_router_info
  command: "/usr/bin/python3 /config/python_scripts/zte_tool.py 3"
  json_attributes:
    - wa_inner_version
    - network_type
    - Z5g_SINR
    - Z5g_rsrp
    - nr5g_action_band
    - nr5g_action_channel
    - lte_rsrq
    - lte_rsrp
    - cell_id
    - lte_snr
    - wan_active_channel
    - wan_active_band
    - wan_ipaddr
    - lte_multi_ca_scell_info
    - monthly_tx_bytes
    - monthly_rx_bytes
    - realtime_rx_thrpt
    - realtime_tx_thrpt
  value_template: "{{ value_json.wa_inner_version }}"
  scan_interval: 10
